### ISSUE TITLE
FTBFS: "No module named html.parser"

### ISSUE THREAD

**Issue by onlyjob** [scp-fs2open/wxLauncher#139]
~~~~
Traceback (most recent call last): 
  File "scripts/onlinehelpmaker.py", line 19, in <module> 
    from helpparsers import Stage2Parser, Stage3Parser, Stage4Parser, Stage5Parser 
  File "/build/freespace2-launcher-wxlauncher-0.11.0+dfsg/scripts/helpparsers.py", line 9, in <module> 
    from html.parser import HTMLParser 
ImportError: No module named html.parser 
~~~~

**Comment by onlyjob** [comment]
I see, `onlinehelpmaker.py` is incompatible with _python2_... Perhaps we need _python3_ on build time and `-DPYTHON_EXECUTABLE=/usr/bin/python3` (found hint in #99).
Not ideal but should work even with default _python2_...

Shouldn't README and/or release notes highlight that Python-3 is a build requirement?
At the moment `ReadMe.md` is outdated as it suggests "Python 2.6+ (but not 3.x)"...

**Comment by MageKing17** [comment]
It supports Python2 if you install the "future" package (`pip install future`), supposedly. On the other hand, making it polymorphic without that package isn't really that difficult... either way, the readme really should've been updated when Python3 was supported.

**Comment by IssMneur** [comment]
Sorry, I missed that the changes had broken python 2.7

**Comment by onlyjob** [comment]
Thanks! :)
