### ISSUE TITLE
Make Launching FRED2 from wxLauncher More Inuitive

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/wxLauncher#156]
Since the move to using AppData for the location of cmdline_fso.cfg, using FRED2 gets a bit tricky to use, as you have to check to both the $FS2PATH directoryand the directory in AppData for the file.

Perhaps have another drop-down box underneath the `FS2 Open executable` drop-down box on the Basic Settings tab. The two boxes would be linked, so if you choose 3.7.4 debug FSO, it'll try to find a 3.7.4 debug FRED2.

**Comment by z64555** [comment]
I have been informed that this feature already exists, but it's hidden from the menu until you press F2 while on the Basic Settings tab. Renaming the Ticket to reflect this.

Instead of hiding the F3 status, there should be a button or otherwise a label that lets us know about this feature.

**Comment by IssMneur** [comment]
I disagree.  We already have too many knobs shown by default for a user to twiddle. We are trying to keep wxLauncher as streamlined as possible and for most users, they don't care about FRED or even understand what it is, so having a drop down for them to select it when they may not even have a FRED binary is just going to confuse the issue.

*F2* is the same key that gets you to the dev tools in FSO, so it seemed appropriate. A better place to mention that *F2* allows you to launch FRED is in the FRED tutorials.
