### ISSUE TITLE
wxlauncher error on fresh build

### ISSUE THREAD

**Issue by skulumani** [scp-fs2open/wxLauncher#157]
Hello I'm trying to install and build wxlauncher on an Ubuntu 16.04 64 bit machine. I downloaded the source for version 10.1 and performed the following steps

1. mkdir build && cd build
2. cmake -DUSE_OPENAL=1 -DCMAKE_INSTALL_PREFIX=/usr/local ../
3. make && make install

Upon completing all of the previous successfully and launching wxlauncher I'm presented with the following error in the GUI. I'm able to click continue through the errors but the launcher will not open the executable. 

Any ideas what I'm doing wrong or suggestions?

~~~
ASSERT INFO:
../include/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

BACKTRACE:
[1] wxFileConfig::Parse(wxTextBuffer const&, bool)
[2] wxFileConfig::wxFileConfig(wxInputStream&, wxMBConv const&)
[3] ModList::ParseModIni(wxString const&, wxString const&, bool)
[4] ModList::ModList(wxWindow*, wxSize&, wxString)
[5] ModsPage::OnTCChanged(wxCommandEvent&)
[6] ModsPage::ModsPage(wxWindow*)
[7] MainWindow::MainWindow()
[8] wxLauncher::OnInit()
[9] wxAppConsoleBase::CallOnInit()
[10] wxEntry(int&, wchar_t**)
[11] main
[12] __libc_start_main
[13] _start

~~~

**Comment by MageKing17** [comment]
> I downloaded the source for version 10.1

...Okay, but do you get the same error if you try to build current master?

**Comment by skulumani** [comment]
@MageKing17 Thanks for the update. Building using the latest master still shows the same error using the default profile. However, I can use/create a different profile and everything seems to work as intended in spite of the original error.

**Comment by asarium** [comment]
It's not an error, only a warning which you can safely skip. It's caused by a bug in wxWidgets.

**Comment by skulumani** [comment]
Thanks for the comment. I appreciate it
