### ISSUE TITLE
wxLauncher doesn't follow fs2_open behavior of writing to ~/.fs2_open

### ISSUE THREAD

**Issue by IssMneur** [scp-fs2open/wxLauncher#93]
_From [zekesula...@gmail.com](https://code.google.com/u/102518650287327435525/) on August 22, 2012 16:59:25_

To reproduce this issue:
1) Place the game binary and/or data directory somewhere your user cannot write (i.e. /opt/fs2_open owned by root).
2) Point wxLauncher at this root directory - it will detect all binaries fine.
3) Configure the game - this stage DOES work as intended, as fs2_open.ini is properly saved to $HOME/.fs2_open
4) Attempt to play the game - wxLauncher fails here.

wxLauncher returns: can't open file '/opt/fs2_open/data/cmdline_fso.cfg' (error 13: Permission denied)

It should write cmdline_fso.cfg to $HOME/.fs2_open like it does the .ini file and like fs2_open itself does for saves and the like.

What version of the wxLauncher are you using: 0.9.1 alpha
What version of fs2_open: 3.6.14 RC7 and SVN build 9130
What mods (and version, if known): MediaVPs 3.6.12 w/ 3.6.14 shaders

What operating system and version: ArchLinux x86_64

Please provide any additional information below:
Sorry for riding on the other issue; I thought they were more related then they were :p

_Original issue: http://code.google.com/p/wxlauncher/issues/detail?id=93_

**Comment by onlyjob** [comment]
I just reproduced FTBFS on Debian using 0.9.6 and reported it as new issue #115 before realising that it was already imported as #93 but mistakenly closed...
